env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} 

name: Publish Package
on:
    release:
        types: [created]
jobs:
    unit-test:
        name: Unit Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install
              run: npm install
            - name: Unir Test
              run: npm test 
    build:
      name: Build
      needs: unit-test
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Clean Install
          run: npm ci
        - name: Build
          run: npm run build
        - name: Upload artifact
          uses: actions/upload-artifact@v3
          with:
            name: service-build
            path: ./dist
    publish:
      name: Publish
      needs: build
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write
      steps:
        - uses: actions/checkout@v3
        - name: Check contents
          run: ls -la
        - uses: actions/setup-node@v4
          with:
            node-version: '16.x'
            registry-url: 'https://npm.pkg.github.com'
            scope: '@fredydlemus'
        - name: Check contents 2
          run: ls -la
        - name: Verify .npmrc configuration
          run: cat ~/.npmrc
        - name: Download artifact
          uses: actions/download-artifact@v3
          with:
            name: service-build
            path: ./dist
        - name: Publish
          run: npm publish
        - name: Display error
          if: failure()
          run: cat /home/runner/.npm/_logs/*.log
        - name: Verify .npmrc configuration
          if: failure()
          run: cat ~/.npmrc