name: Publish Package
on:
    release:
        types: [created]
jobs:
    unit-test:
        name: Unit Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install
              run: npm install
            - name: Unir Test
              run: npm test 